@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":StockPal" as stockpal STOCKPAL_COLOR
Participant ":Parser" as parser PARSER_COLOR
Participant ":NewCommand" as command COMMANDS_COLOR
Participant ":Storage" as storage STORAGE_COLOR



user -[USER_COLOR]> ui : "new n/Chocolate q/100 p/2.00 d/Tobelerone"
activate ui UI_COLOR

ui -[UI_COLOR]> stockpal : "new ..."

activate stockpal STOCKPAL_COLOR

stockpal -[STOCKPAL_COLOR]> parser : parseCommand("new ...")
activate parser PARSER_COLOR



parser -[PARSER_COLOR]> command : new NewCommand(pid, name, quantity, price, description)
activate command COMMANDS_COLOR
parser <--[COMMANDS_COLOR] command
deactivate command

parser --[PARSER_COLOR]> stockpal : command : NewCommand
deactivate parser

stockpal -[STOCKPAL_COLOR]> command : execute()
activate command COMMANDS_COLOR

note over command
    Add product details
end note

command -[COMMANDS_COLOR]> ui : printAddSuccessMessage()
user <-[UI_COLOR] ui : "Product has been added."
ui [UI_COLOR]--> command
stockpal <--[COMMANDS_COLOR] command
deactivate command

stockpal -[STOCKPAL_COLOR]> storage : saveData(productList)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> stockpal
deactivate storage

destroy command
@enduml