@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":NewCommand" as command COMMANDS_COLOR
/'Participant ":Product" as product PRODUCT_COLOR'/
Participant ":ProductList" as productlist PRODUCTLIST_COLOR
Participant ":UI" as ui UI_COLOR

-> command : execute()
activate command COMMANDS_COLOR

command -> productlist
activate productlist PRODUCTLIST_COLOR


productlist -> productlist : checkForRepeated(name)
activate productlist PRODUCTLIST_COLOR

note over productlist
     Throws DuplicateProductNameException
     if name already exists in product list
end note

productlist --> productlist
deactivate productlist

command <-- productlist
deactivate productlist

 command -> command : createProduct(name, quantity, price, description)
 activate command COMMANDS_COLOR

 command --> command : newProduct : Product
 deactivate command COMMANDS_COLOR


 command -> productlist : addProduct(newProduct)
 activate productlist PRODUCTLIST_COLOR


 command <-- productlist
 deactivate productlist

 command -> ui : printAddSuccessMessage()
 activate ui UI_COLOR
 command <-- ui
 deactivate ui


<-- command
deactivate command

@enduml