@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class Exceptions EXCEPTIONS_COLOR
    Class Data DATA_COLOR
    Class UI UI_COLOR
    Class Parser PARSER_COLOR
    Class Storage STORAGE_COLOR
    Class Command COMMANDS_COLOR
    Class StockPal STOCKPAL_COLOR
    Class Common COMMON_COLOR
}

Class "<$user>" as User COMMANDS_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -right[UI_COLOR]-> StockPal
StockPal -down[STOCKPAL_COLOR]-> Command
StockPal -right[STOCKPAL_COLOR]-> Parser
Parser .up[PARSER_COLOR]-> StockPal
Parser -right[hidden]-> Command
Command .down[hidden]-> Parser
Command -[COMMANDS_COLOR]> Data
StockPal -right[STOCKPAL_COLOR]-> Storage
Exceptions -up[hidden]-> Common

Storage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
