@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor COMMANDS_COLOR
skinparam classBackgroundColor COMMANDS_COLOR

package Commands as CommandPackage {
    Class "{abstract}\nCommand" as command
    Class "DeleteCommand" as delete
    Class "EditCommand" as edit
    Class "ExitCommand" as exit
    Class "FindCommand" as find
    Class "HelpCommand" as help
    Class "HistoryCommand" as history
    Class "InflowCommand" as inflow
    Class "{abstract}\nListActionCommand" as action
    Class "ListCommand" as list
    Class "NewCommand" as new
    Class "OutflowCommand" as outflow
    Class "{abstract}\nTransactionActionCommand" as transaction
}

StockPal -.> command : executes >
Parser -.> command : creates >
command -up.> UI : prints output >

action -right-|> command
transaction -left-|> command
exit -up-|> command
help -up-|> command
help -down[hidden]-> new
find -up[hidden]-> edit

new -up-|> action
edit -up-|> action
find -up-|> action
list -up-|> action

inflow -up-|> transaction
delete -up-|> transaction
delete -up[hidden]-|> inflow
history -up-|> transaction
outflow -up-|> transaction
history -up[hidden]-> outflow

@enduml