@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":StockPal" as stockpal STOCKPAL_COLOR
Participant ":UI" as ui UI_COLOR
Actor User as user USER_COLOR
Participant ":Parser" as parser PARSER_COLOR
Participant ":XYZCommand" as command COMMANDS_COLOR
Participant ":Storage" as storage STORAGE_COLOR

activate stockpal STOCKPAL_COLOR

stockpal -[STOCKPAL_COLOR]> ui : getUserInput()
activate ui UI_COLOR

ui -[STOCKPAL_COLOR]> user : Get user input
user --[USER_COLOR]> ui : userInput : String

ui --[UI_COLOR]> stockpal : userInput : String
deactivate ui

stockpal -[STOCKPAL_COLOR]> parser : parseCommand(userInput)
activate parser PARSER_COLOR

note over of command
    XYZ is a placeholder for
    the specific command name.
    e.g. NewCommand
end note

create command
parser -[PARSER_COLOR]> command : XYZCommand()
activate command COMMANDS_COLOR

command --[COMMANDS_COLOR]> parser : command : XYZCommand
deactivate command

parser --[PARSER_COLOR]> stockpal : command : XYZCommand
deactivate parser

stockpal -> stockpal : checkCommandType(command)

activate stockpal STOCKPAL_COLOR

alt ListAction command
    stockpal -[STOCKPAL_COLOR]> command : execute(productList)
    activate command COMMANDS_COLOR

    note over command
        Execute ListAction command
    end note

    stockpal <--[COMMANDS_COLOR] command
    deactivate command

    opt NewCommand or EditCommand
        stockpal -[STOCKPAL_COLOR]> storage : saveData(productList)
        activate storage STORAGE_COLOR
        storage -[STORAGE_COLOR]> storage : Save to file
        activate storage STORAGE_COLOR

        storage --[STORAGE_COLOR]> storage
        deactivate storage

        storage --[STORAGE_COLOR]> stockpal
        deactivate storage
    end
else TransactionAction command
    stockpal -[STOCKPAL_COLOR]> command : execute(productList, transactionList)
    activate command COMMANDS_COLOR

    note over command
       Execute TransactionAction command
    end note

    stockpal <--[COMMANDS_COLOR] command
    deactivate command

    opt DeleteCommand or InflowCommand or OutflowCommand
        stockpal -[STOCKPAL_COLOR]> storage : saveData(productList), save(transactionList)
        activate storage STORAGE_COLOR
        storage -[STORAGE_COLOR]> storage : Save to file
        activate storage STORAGE_COLOR

        storage --[STORAGE_COLOR]> storage
        deactivate storage

        storage --[STORAGE_COLOR]> stockpal
        deactivate storage
    end
else HelpCommand or ExitCommand
    stockpal -[STOCKPAL_COLOR]> command : execute()
    activate command COMMANDS_COLOR

    note over command
       Execute command
    end note

    stockpal <--[COMMANDS_COLOR] command
    deactivate command

end

stockpal --> stockpal
deactivate stockpal

destroy command

@enduml
