@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":DeleteCommand" as command COMMANDS_COLOR
Participant ":ProductList" as productlist PRODUCTLIST_COLOR
Participant ":TransactionList" as transactionlist TRANSACTIONLIST_COLOR
Participant ":UI" as ui UI_COLOR

-> command : execute()
activate command COMMANDS_COLOR

command -> productlist : deleteProduct(PID)
activate productlist PRODUCTLIST_COLOR
productlist -> productlist : findProductIndex(PID)
activate productlist PRODUCTLIST_COLOR
productlist --> productlist : productIndex: int
deactivate productlist

productlist -> productlist : products.remove(productIndex)
activate productlist PRODUCTLIST_COLOR
productlist --> productlist
deactivate productlist
productlist --> command
deactivate

command -> transactionlist : deleteTransactions(PID)
activate transactionlist TRANSACTIONLIST_COLOR
transactionlist --> command
deactivate transactionlist

command -> ui : printDeleteSuccessMessage()
activate ui UI_COLOR
ui --> command
deactivate ui


<-- command
deactivate command

@enduml