@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":FindCommand" as command COMMANDS_COLOR
Participant ":ProductList" as productlist PRODUCTLIST_COLOR
Participant ":UI" as ui UI_COLOR

activate command COMMANDS_COLOR
-> command : execute()

command -> productlist : findKeyword(productList, keyword)
activate productlist PRODUCTLIST_COLOR
productlist --> productlist: MatchingProductList


productlist -> ui : printListTasks(MatchingProductList)
deactivate productlist

@enduml
