@startuml

hide circles
skinparam classAttributeIconSize 0

package "seedu.stockpal.commands" {
    class FindCommand {
        - keyword: String

        + FindCommand(keyword: String)
        + execute(productList: ProductList): void
    }
}

@enduml