@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":StockPal" as stockpal STOCKPAL_COLOR
Participant ":Parser" as parser PARSER_COLOR
Participant ":HistoryCommand" as command COMMANDS_COLOR
Participant ":Storage" as storage STORAGE_COLOR



user -[USER_COLOR]> ui : "history 1"
activate ui UI_COLOR

ui -[UI_COLOR]> stockpal : "history 1"
activate stockpal STOCKPAL_COLOR

stockpal -[STOCKPAL_COLOR]> parser : parseCommand("history 1")
activate parser PARSER_COLOR


parser -[PARSER_COLOR]> command : new HistoryCommand(pid)
activate command COMMANDS_COLOR
parser <--[COMMANDS_COLOR] command
deactivate command

parser --[PARSER_COLOR]> stockpal : command : HistoryCommand
deactivate parser

stockpal -[STOCKPAL_COLOR]> command : execute()
activate command COMMANDS_COLOR

note over command
    Find past transactions
end note

command -[COMMANDS_COLOR]> ui : printPastTransactions(TransactionList)
user <-[UI_COLOR] ui :
ui [UI_COLOR]--> command
stockpal <--[COMMANDS_COLOR] command
deactivate command

@enduml