@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":HistoryCommand" as command COMMANDS_COLOR
Participant ":TransactionList" as transactionlist PRODUCTLIST_COLOR
Participant ":UI" as ui UI_COLOR


-> command : execute()
activate command COMMANDS_COLOR

command -> transactionlist : findTransactions(transactionList, productIndex);
activate transactionlist PRODUCTLIST_COLOR

transactionlist -> ui : printListTasks(PastTransactions)
activate ui UI_COLOR
ui --[UI_COLOR]> transactionlist
deactivate ui UI_COLOR


transactionlist --[PRODUCTLIST_COLOR]> command



@enduml
