@startuml
!include style.puml

Participant ":InflowCommand" as command COMMANDS_COLOR
Participant ":ProductList" as productlist PRODUCTLIST_COLOR
Participant ":UI" as ui UI_COLOR

activate command COMMANDS_COLOR

command -> productlist : increaseAmountCaller(pid, increaseAmt)
activate productlist PRODUCTLIST_COLOR

productlist -> ui : printToScreen
deactivate productlist
activate ui UI_COLOR

@enduml