@startuml
!include style.puml

Participant ":InflowCommand" as command COMMANDS_COLOR
Participant ":ProductList" as productlist PRODUCTLIST_COLOR
Participant ":UI" as ui UI_COLOR

-> command : execute()
activate command COMMANDS_COLOR

command -> productlist : increaseAmountCaller(pid, increaseAmt)
activate productlist PRODUCTLIST_COLOR

productlist -> ui : printToScreen
activate ui UI_COLOR
ui --[UI_COLOR]> productlist
deactivate ui UI_COLOR

productlist --[PRODUCTLIST_COLOR]> command
deactivate productlist

<-- command
deactivate command

@enduml