@startuml

hide circles
skinparam classAttributeIconSize 0

package "seedu.stockpal.commands" {
    class InflowCommand {
        - pid: Pid
        - amountToIncrease: Integer
        - time: LocalDateTime

        + execute(productList: ProductList): void
        - createTransaction(pid: Pid, amountToIncrease: Integer, time: LocalDateTime): Transaction
    }
}

package "seedu.stockpal.data.product" {
    class Quantity {
        + updateIncreaseQuantity(increaseQuantity: Integer): void
        .. Other methods ..
    }

}

package "seedu.stockpal.data" {
    class ProductList {
            + increaseAmount(index: Integer, amount: Integer): void
            .. Other methods ..
    }
}

InflowCommand -> ProductList: increaseAmount(index, amountToIncrease)
ProductList --> Quantity: updateIncreaseQuantity(amountToIncrease)


@enduml
