@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":ListCommand" as command COMMANDS_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":ProductList" as productlist PRODUCTLIST_COLOR

activate command COMMANDS_COLOR
-> command : execute()

alt Product list is empty
command -> ui : printEmptyListMessage()
activate ui UI_COLOR
command <-- ui
deactivate ui
else
    command -> command : sortListAccordingly(newList)
    activate command COMMANDS_COLOR
    alt Sort list by quantity
        command -> productlist : products.sort(SortByQuantity())
        activate productlist PRODUCTLIST_COLOR
        command <-- productlist
        deactivate productlist
    else Sort list by name
        command -> productlist : products.sort(SortByName())
        activate productlist PRODUCTLIST_COLOR
        command <-- productlist
        deactivate productlist
    else Sort list by PID by default
    end
    command --> command
    deactivate command
end
command -> ui : printListTask(newList)
activate ui UI_COLOR
ui --> command
deactivate ui

<-- command
deactivate command
@enduml