@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam classBackgroundColor UI_COLOR

package Parser as ParserPackage {
    Class "Parser" as Parser PARSER_COLOR
}

Class Ui UI_COLOR
Class XYZCommand COMMANDS_COLOR
Class StockPal STOCKPAL_COLOR

StockPal ..> Ui : gets User Input from >
StockPal -left.> Parser : passes User Input to >
Parser -down.> XYZCommand : creates

note bottom of XYZCommand : Based on the type of command is passed to Parser,\n the corresponding Command object is created.

@enduml