@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {
    package TransactionStorage as TransactionStoragePackage {
        Class "JsonWriter" as JsonWriter
        Class "JsonReader" as JsonReader
        Class "TransactionStorage" as TransactionStorage
    }
    Class "CsvWriter" as CsvWriter

    Class "Storage" as Storage

    Class "CsvReader" as CsvReader
}

Class HiddenOutside #FFFFFF
Class HiddenOuts #FFFFFF
HiddenOutside ..> Storage
HiddenOuts .> TransactionStorage
HiddenOuts -[hidden].> Storage

Storage -down..> CsvWriter : Uses >
Storage -down..> CsvReader : Uses >

TransactionStorage -down..> JsonWriter : Uses >
TransactionStorage -down..> JsonReader : Uses >

@enduml